version: '1'
networks:
  ps_network:
    driver: bridge

services:
  bdd:
    image: "postgres:15.1"
    container_name: bdd
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - ./bd/build_db.sql:/docker-entrypoint-initdb.d/build_db.sql
      - ./bd/fill_db.sql:/docker-entrypoint-initdb.d/fill_db.sql
      - ps_bdd_vol:/var/lib/postgresql/data
    networks:
      ps_network:
        aliases:
          - bdd

volumes:
  ps_bdd_vol: